### ISSUE TITLE
Reducing Gauge Size in Vertical Stack

### ISSUE THREAD

**Issue by royf007** [selvalt7/modern-circular-gauge#103]
Is there a way to reduce the size of the gauge within it's container card?  I have a vertical stack.  I've tried card_mod with width and height on the ha-card style, but can't seem to get this to work.  It's fine in a desktop browser, but looks huge in a mobile browser.

<img width="495" alt="Image" src="https://github.com/user-attachments/assets/5cf99ef1-eb45-4df8-a70d-85d4d5c61b6e" />

**Comment by selvalt7** [comment]
Setting `max-height` and `max-width` instead seems to work in card_mod but you could also add !important to the `height` and `width` property. Either way both methods should work.
```css
ha-card {
  height: 50% !important; /* This works */
  max-height: 50%; /* This also works */
}
```
