### ISSUE TITLE
Decimal places and unit not displayed when color segments are defined

### ISSUE THREAD

**Issue by spejbel** [selvalt7/modern-circular-gauge#45]
**Description:**
When no color segments (segments) are defined, the values of both sensors are correctly displayed with decimal places and the unit (°C).
However, as soon as color segments are added, the first sensor value is only shown as an integer. The decimal places and unit are completely missing.

with color segments
![Image](https://github.com/user-attachments/assets/2ab14b4d-7b09-4b46-8306-f61b3908b919)

without color segments
![Image](https://github.com/user-attachments/assets/4ddc47f2-a232-401f-846d-580dadf3fc64)

**Expected Behavior:**
Sensor data should be fully displayed (including decimal places and unit), regardless of the color segments being defined.

**Current Behavior:**
Without color segments: Values are correctly displayed with decimal places and unit.
With color segments: The first sensor value only shows whole numbers without decimal places and the unit.

**Steps to Reproduce:**
Create a custom:modern-circular-gauge card with a sensor and no color segments – values are displayed correctly.
Add color segments (segments) to the configuration.
Observe that the decimal places and unit are no longer displayed for the first sensor value.

**Used Version:**
modern-circular-gauge: v0.6.1
Home Assistant Version: Core 2025.1.2, Supervisor 2024.12.3, Operating System 11.4, Frontend 20250109.0
Browser/Platform: Windows 11 24H2, Version 132.0.6834.83

**The issue is reproducible.**
The problem may be related to how the color segments affect the rendering of the sensor value.
Tested with multiple sensors and different configurations – the behavior remains consistent.

**Example Configuration**

```
type: custom:modern-circular-gauge
entity: sensor.temp_A
segments:
  - from: 12
    label: "12"
    color:
      - 0
      - 76
      - 153
  - from: 15
    label: "15"
    color:
      - 51
      - 153
      - 255
  - from: 17
    label: "17"
    color:
      - 102
      - 178
      - 255
  - from: 19
    label: "19"
    color:
      - 204
      - 229
      - 255
  - from: 20
    label: "20"
    color:
      - 255
      - 165
      - 0
  - from: 23
    label: "23"
    color:
      - 255
      - 140
      - 0
  - from: 26
    label: "26"
    color:
      - 255
      - 69
      - 0
  - from: 29
    label: "29"
    color:
      - 220
      - 20
      - 60
  - from: 32
    label: "32"
    color:
      - 178
      - 0
      - 0
unit: °C
min: 12
max: 34
needle: true
smooth_segments: true
secondary:
  entity: sensor.temp_B
  unit: °C
  show_gauge: outter
  min: 12
  max: 34
  segments:
    - from: 12
      label: "12"
      color:
        - 0
        - 76
        - 153
    - from: 15
      label: "15"
      color:
        - 51
        - 153
        - 255
    - from: 17
      label: "17"
      color:
        - 102
        - 178
        - 255
    - from: 19
      label: "19"
      color:
        - 204
        - 229
        - 255
    - from: 20
      label: "20"
      color:
        - 255
        - 165
        - 0
    - from: 23
      label: "23"
      color:
        - 255
        - 140
        - 0
    - from: 26
      label: "26"
      color:
        - 255
        - 69
        - 0
    - from: 29
      label: "29"
      color:
        - 220
        - 20
        - 60
    - from: 32
      label: "32"
      color:
        - 178
        - 0
        - 0
  state_size: small
  needle: true
header_position: bottom
name: " "
```

Thank you for looking into this issue. I am happy to provide further details or assist with additional testing.

**Comment by erikgeurts** [comment]
I'm not able to reproduce this, here's one of my gauges:

![Image](https://github.com/user-attachments/assets/fdb54ff3-ffac-4c12-a549-3ba13400bf55)

It looks like the difference between your code and mine is that you have defined a "label" for each segment, whereas I haven't. Here's a snippet from my code:

```
segments:
  - from: 0
    color:
      - 0
      - 0
      - 0
  - from: 1
    color:
      - 251
      - 65
      - 65
  - from: 1.7
    color:
      - 255
      - 193
      - 69
  - from: 2.4
    color:
      - 236
      - 232
      - 82
  - from: 3
    color:
      - 92
      - 179
      - 56
```

Perhaps try removing those labels and see what happens?
