### ISSUE TITLE
How to "mini" / chips like gauges?

### ISSUE THREAD

**Issue by tioan** [selvalt7/modern-circular-gauge#52]
How i can create chips like gauges as shown in the example?

<img width="399" alt="Image" src="https://github.com/user-attachments/assets/1c99fb60-2e29-4fea-9a6e-a1bad346db04" />

**Comment by selvalt7** [comment]
Badges can be configured through the ui.

Example config:
```yaml
type: custom:modern-circular-gauge-badge
entity: sensor.cool_sensor
show_name: true
show_icon: true
```
Not to confuse these with mushroom chips, they are different.
