### ISSUE TITLE
Override primary display text or allow swapping/hiding options

### ISSUE THREAD

**Issue by D3SOX** [selvalt7/modern-circular-gauge#74]
I would like a way to override the primary display with a template

Alternatively, it could be an option to swap the secondary and primary display and an option to hide the primary display

My usecase is 

![Image](https://github.com/user-attachments/assets/14c31e43-92b8-4779-9410-49edf9a0a806)

I currently have

```yaml
type: custom:modern-circular-gauge
entity: sensor.io_series_9_duration
min: 0
max: 180
needle: true
name: Brushing Time
unit: s
segments:
  - from: 0
    color: red
  - from: 60
    color: yellow
  - from: 120
    color: green
secondary:
  entity: sensor.brushing_time_formatted
visibility:
  - condition: state
    entity: sensor.io_series_9_brushing_mode
    state_not: tongue cleaning

```
