### ISSUE TITLE
Add option for triple gauge?

### ISSUE THREAD

**Issue by Nedevski** [selvalt7/modern-circular-gauge#82]
**Is your feature request related to a problem? Please describe.**
I have a server room that has a UPS and two servers (this can be different for anyone).

**Describe the solution you'd like**
I would like to have the dual gauge setup, but with three circles. Either without a label for the third circle, or with a label above the main sensor text. This will help people like me who like their dashboard as concise as possible.

**Describe alternatives you've considered**
I could use two cards, but with uneven sensor count that's wasting space.

**Comment by elRadix** [comment]
### **Feature Request: Tertiary Gauge Support**
**Title**: "Add support for tertiary gauge (e.g., EV battery percentage)"  
**Description**:  
Allow a third concentric gauge to display additional metrics like EV battery state of charge, while maintaining existing secondary gauge functionality.

**Use Case**:  
```yaml
type: custom:modern-circular-gauge
entity: sensor.ev_power
# Primary gauge (power)
segments: [...] 

# Secondary gauge (daily energy)
secondary:
  entity: sensor.ev_daily_energy
  show_gauge: inner
  # ...

# Proposed tertiary gauge (battery %)
tertiary:
  entity: sensor.ev_battery_level
  show_gauge: innermost  # New position
  unit: "%"
  min: 0
  max: 100
  segments:
    - from: 0
      color: [255, 0, 0]
    - from: 20
      color: [255, 165, 0]
    - from: 80
      color: [0, 255, 0]
```

**Suggested Parameters**:
```yaml
tertiary:
  entity: string         # Required
  show_gauge: boolean|"innermost"
  width: number          # Default: auto-calculated
  offset: number         # Pixel gap from secondary gauge
  segments: []           # Color thresholds
  unit: string           # Override unit_of_measurement
```

**Visual Concept**:
```
[ Battery % (innermost) ]
[ Daily kWh (inner)     ]
[ Current kW (outer)    ]
```

---

### **Minimal EV Config Example**
```yaml
- type: custom:modern-circular-gauge
  entity: sensor.alfen_active_power_total_socket_1
  name: "EV Status"
  height: 240  # Increased for 3 gauges
  
  # Primary gauge (power)
  segments: 
    - from: 0
      color: [18, 147, 94]
    - from: 3000
      color: [244, 228, 0]
  
  # Secondary gauge (daily energy)
  secondary:
    entity: sensor.alfen_daily_energy
    show_gauge: inner
    max: 40
  
  # Proposed tertiary gauge (battery)
  tertiary:
    entity: sensor.ev_battery_level
    show_gauge: innermost
    unit: "%"
    segments:
      - from: 0
        color: [222, 49, 99]  # Red
      - from: 20
        color: [255, 117, 20] # Orange
      - from: 50
        color: [244, 228, 0]  # Yellow
      - from: 80
        color: [18, 147, 94]  # Green
```

**Key Benefits**:
1. **Space Efficient**: Shows 3 metrics in one card
2. **Consistent Styling**: Matches existing gauge behavior
3. **Logical Hierarchy**:  
   - Outer: Real-time power  
   - Middle: Daily total  
   - Inner: Battery state

Would you like me to:
1. Draft the full GitHub issue text?
2. Provide a mockup image description?
3. Suggest alternative implementations?
