### ISSUE TITLE
Negative number not showing correctly

### ISSUE THREAD

**Issue by Protoncek** [selvalt7/modern-circular-gauge#85]
**Describe the bug**
When i set "min" value below zero whole foreground "thing" rotates to the right (starts from zero, not from MIN), while it should start at the bottom left, like it does when i set min to zero. Am i doing something wrong in settings? My code:

```
type: custom:modern-circular-gauge
entity: sensor.temperature_outside
unit: °C
name: Temperature
gauge_foreground_style:
  color: adaptive
  opacity: 70%
  width: 5
gauge_background_style:
  width: 2
  color: adaptive
min: -20
max: 40
smooth_segments: true
show_icon: false
show_gauge: null
segments:
  - from: -20
    color: blue
  - from: 0
    color: cyan
  - from: 10
    color: green
  - color: red
    from: 20
secondary: {}
header_position: bottom
needle: false
show_header: true
show_state: true
show_unit: true
adaptive_icon_color: false
adaptive_state_color: false

```

![Image](https://github.com/user-attachments/assets/01f931ee-3d54-4d91-892c-db2ca995b4b6)

**Environment:**
 - OS: Winows]
 - Edge
 - HA Version 2025.4.4
 - Card Version 0.8.1
