### ISSUE TITLE
tap_action navigate

### ISSUE THREAD

**Issue by limatango79** [selvalt7/modern-circular-gauge#96]
Would it be possible to implement a tap_action:navigate-feature?
I use the modern-circular-gauge on the dashboard for displaying the outside temperature.
It would be great if I could navigate to the weather page by tapping on the card.

**Comment by selvalt7** [comment]
This feature is already implemented and is configurable through the UI.
Here's an YAML example:
```yaml
tap_action:
  action: navigate
  navigation_path: /lovelace/weather
```
